### PR TITLE
Add migrations to fix issue #18.

### PR DESCRIPTION
**Pull request by Heleen**
Fixes https://github.com/evonove/django-stored-messages/issues/18.

Add migrations to fix the 'Django 1.8: relation "auth_user" does not exist' bug.

As of django 1.7 models without migrations can no longer have foreign keys to models that do have migrations.
See https://docs.djangoproject.com/en/1.7/topics/migrations/#dependencies for more information.

I have tested this PR with Python 2.7 and django 1.4 up until 1.8. However I couldn't get `tox` to work:

    ERROR: InvocationError: '/srv/django-stored-messages/.tox/py27-django18/bin/coverage run -a runtests.py'

So no tests for Python 3.
I also had to install some extra packages to run the tests in the first place.

Anyone ideas on why Tox/Travis tests fail?

### CODE REVIEW

**Comment by Heleen** [comment]
I have decided to close and remove this pull request.

Because the URL field in version 1.3 was added without the use of migrations it will require a lot more to add migrations now than just adding an initial migration.
Users of a version prior 1.3 that already the tables in their database will need both an initial and a migration for the added field with only the initial fake-applied. Users who stepped in at version 1.3 that already have the tables in their database will need to fake apply the second migration that adds the URL field as well.

There isn't enough time our own project for me to properly work this out (even in a forked version), so we have decided to only support our own case (our project used version 1.1) and simply add migrations to our own app as is suggested in an [issue](https://github.com/evonove/django-oauth-toolkit/issues/204#issuecomment-77984967) on django-oauth-toolkit.

**Comment by xrmx** [comment]
@Heleen it's the user duty to have the db in sync with 1.3 before switching to a new release. So your pull request looks fine to me

**Comment by palazzem** [comment]
Can't merge this PR anymore (the repository seems deleted). At this point I'll work on a two steps migration (the first for the database prior the ``url`` field change and the latter just for the ``url`` field) with the proper documentation. In this way, users may know how to migrate from versions:
- ``1.2.0`` (or earlier) to ``1.4.0``
- ``1.3.0`` to ``1.4.0``

Anyway, thanks @Heleen for your previous PR and sorry if we didn't have time for a code review (or simply for debating about the PR). Because you've raised this issue, I'll add your name at least in the commit message.

Cheers.

**Comment by Heleen** [comment]
Thanks everyone (and especially @palazzem) for fixing this after all. Much appreciated! Sorry for deleting my fork and causing you extra work, I should have given you some extra time to work things through.

**Comment by palazzem** [comment]
Don't worry @Heleen ! :D
Hope that the "[migration guide][1]" is useful for general use cases. If we'll find reasonable corner cases, I'll take care of keeping this doc updated.

Let us know if you and your team will find any further issues.
Thank you!

[1]: http://django-stored-messages.readthedocs.org/en/latest/migrations.html

**Pull request closed without merging**
