### PR TITLE
Fix stuff for django 1.9

### PR DESCRIPTION
**Pull request by xrmx**

### CODE REVIEW

**Comment by palazzem** [comment]
Hi @xrmx ,
I'm looking at your PR and it looks good. Anyway I need to apply some minor changes on master to let tests work again (minor issues tox-related) and to define properly a compatibility table (at least for the 1.3.x releases and for the new 2.0 release that includes your changes).

After that, I'll let you know when the PR will be merged.
Thank you!

**Comment by palazzem** [comment]
The PR was OK. There are some problems with the ``stored_messages`` public API that creates many problems with the new Django 1.9 loading mechanism. Actually everything works thanks to your patch but we may think to change the API in the future (in a 2.0 release).

I'll proceed updating the test matrix, removing the compatibility module where necessary so that a new version can be released.

Cheers and thanks for your code! :)

**Comment by xrmx** [comment]
@palazzem Thanks. BTW could you please merge this too before cutting 2.0? https://github.com/evonove/django-stored-messages/pull/20

**Comment by palazzem** [comment]
Sure! Thank you for pointing that a PR was already available, since adding the initial migrations is on our roadmap.

**Comment by xrmx** [comment]
@palazzem firendly ping for a release that would work with supported django versions :)

**Comment by palazzem** [comment]
Eheheh, you're right! I'll work on it tomorrow with proper merges and release :)

**Comment by palazzem** [comment]
Hi @xrmx ,
I've release ``stored_messages`` version [1.4.0][1] that includes your Django 1.9 support, together with Django migrations. I've also introduced a [new section in the documentation][2] to migrate from an earlier version of ``stored_message`` to ``1.4.0``.

This section doesn't cover any corner case or specific-developer issues, but at least solves common problems (such as know if the developer should fake all migrations or only the first one).

Let me know if you find any serious issue or if you have any idea to improve the documentation.
Best.

[1]: https://github.com/evonove/django-stored-messages/releases/tag/1.4.0
[2]: http://django-stored-messages.readthedocs.org/en/latest/migrations.html

**Comment by xrmx** [comment]
Thanks @palazzem!

**Pull request merged**
